# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'user_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12user_service.proto\x12\x0cuser_service\"+\n\x17\x42\x61tchGetUserInfoRequest\x12\x10\n\x08user_ids\x18\x01 \x03(\x03\"\xe0\x01\n\x18\x42\x61tchGetUserInfoResponse\x12@\n\x05users\x18\x01 \x03(\x0b\x32\x31.user_service.BatchGetUserInfoResponse.UsersEntry\x12\x11\n\tnot_found\x18\x02 \x03(\x03\x12\x12\n\nerror_code\x18\x03 \x01(\t\x12\x15\n\rerror_message\x18\x04 \x01(\t\x1a\x44\n\nUsersEntry\x12\x0b\n\x03key\x18\x01 \x01(\x03\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.user_service.UserInfo:\x02\x38\x01\"-\n\x08UserInfo\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12\x10\n\x08username\x18\x02 \x01(\t2p\n\x0bUserService\x12\x61\n\x10\x42\x61tchGetUserInfo\x12%.user_service.BatchGetUserInfoRequest\x1a&.user_service.BatchGetUserInfoResponseB\x19Z\x17github.com/cs6650/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\027github.com/cs6650/proto'
  _globals['_BATCHGETUSERINFORESPONSE_USERSENTRY']._loaded_options = None
  _globals['_BATCHGETUSERINFORESPONSE_USERSENTRY']._serialized_options = b'8\001'
  _globals['_BATCHGETUSERINFOREQUEST']._serialized_start=36
  _globals['_BATCHGETUSERINFOREQUEST']._serialized_end=79
  _globals['_BATCHGETUSERINFORESPONSE']._serialized_start=82
  _globals['_BATCHGETUSERINFORESPONSE']._serialized_end=306
  _globals['_BATCHGETUSERINFORESPONSE_USERSENTRY']._serialized_start=238
  _globals['_BATCHGETUSERINFORESPONSE_USERSENTRY']._serialized_end=306
  _globals['_USERINFO']._serialized_start=308
  _globals['_USERINFO']._serialized_end=353
  _globals['_USERSERVICE']._serialized_start=355
  _globals['_USERSERVICE']._serialized_end=467
# @@protoc_insertion_point(module_scope)
